language: java
jdk:
  - openjdk8

branches: # 어느 브랜치가 푸시될때 CI 할거냐
  only:
    - master

# Travis CI 서버의 Home
cache:  # 의존성 캐싱
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시될때 실행될 스크립트
script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - admin@oreumdiary.com

