version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    
# codedeploy 단계에서 실행할 명령어 지정
hooks:
  ApplicationStart:    # ApplicationStart 단계에서 deploy.sh파일을 ec2-user권한으로 실행해라. (타임아웃60)
    - location: deploy.sh
      timeout: 60
      runas: ec2-user
